name: scheduled_run

on:
  schedule:
    - cron: '10 9 * * *'  # Runs every day at 2:40 PM IST
  workflow_dispatch:       # Optional: allows manual run

jobs:
  scheduled_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "This runs at 2:40 PM IST (09:10 UTC)"
