name: scheduled_run

on:
  schedule:
    - cron: '10 12* * *'  # 2:40 PM IST
  workflow_dispatch:

jobs:
  scheduled_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Running at 2:40 PM IST (09:10 UTC)"
